version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_tasks
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tasks_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app_tasks
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/tasks_db
    depends_on:
      - db
